/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHqRouteImport } from './routes/_authenticated/hq'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated/stores'
import { Route as AuthenticatedAuditAuditIdRouteImport } from './routes/_authenticated/audit.$auditId'
import { Route as AuthenticatedStoreStoreIdRouteImport } from './routes/_authenticated/store.$storeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHqRoute = AuthenticatedHqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditAuditIdRoute =
  AuthenticatedAuditAuditIdRouteImport.update({
    id: '/audit/$auditId',
    path: '/audit/$auditId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoreStoreIdRoute =
  AuthenticatedStoreStoreIdRouteImport.update({
    id: '/store/$storeId',
    path: '/store/$storeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hq': typeof AuthenticatedHqRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/audit/$auditId': typeof AuthenticatedAuditAuditIdRoute
  '/store/$storeId': typeof AuthenticatedStoreStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hq': typeof AuthenticatedHqRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/audit/$auditId': typeof AuthenticatedAuditAuditIdRoute
  '/store/$storeId': typeof AuthenticatedStoreStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/hq': typeof AuthenticatedHqRoute
  '/_authenticated/stores': typeof AuthenticatedStoresRoute
  '/_authenticated/audit/$auditId': typeof AuthenticatedAuditAuditIdRoute
  '/_authenticated/store/$storeId': typeof AuthenticatedStoreStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/hq' | '/stores' | '/audit/$auditId' | '/store/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/hq' | '/stores' | '/audit/$auditId' | '/store/$storeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/hq'
    | '/_authenticated/stores'
    | '/_authenticated/audit/$auditId'
    | '/_authenticated/store/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hq': {
      id: '/_authenticated/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof AuthenticatedHqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/$auditId': {
      id: '/_authenticated/audit/$auditId'
      path: '/audit/$auditId'
      fullPath: '/audit/$auditId'
      preLoaderRoute: typeof AuthenticatedAuditAuditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store/$storeId': {
      id: '/_authenticated/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/store/$storeId'
      preLoaderRoute: typeof AuthenticatedStoreStoreIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHqRoute: typeof AuthenticatedHqRoute
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRoute
  AuthenticatedAuditAuditIdRoute: typeof AuthenticatedAuditAuditIdRoute
  AuthenticatedStoreStoreIdRoute: typeof AuthenticatedStoreStoreIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHqRoute: AuthenticatedHqRoute,
  AuthenticatedStoresRoute: AuthenticatedStoresRoute,
  AuthenticatedAuditAuditIdRoute: AuthenticatedAuditAuditIdRoute,
  AuthenticatedStoreStoreIdRoute: AuthenticatedStoreStoreIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
