UPDATE public.checklist_items c SET code=v.code, text=v.text, weight=v.weight, hint=v.hint
FROM (VALUES
('General',1,'SD1','All customers greeted properly and welcomed as per process.',2,NULL),
('General',2,'SD2','Store is clean; all equipment is clean.',2,NULL),
('General',3,'SD3','Store updates sale chart and temperature chart; team is aware of sales.',4,NULL),
('General',4,'SD4','Store is taking customer details and collecting feedback.',3,NULL),
('General',5,'SD5a','All orders punched in GAAP before handover of product to customer.',2,NULL),
('General',6,'SD5b','All files (petty cash / MIS / GOGS report) updated.',2,NULL),
('General',7,'SD6','No shortage and no excess stock at store, as per system.',2,NULL),
('Sales & Customer',1,'SC1','Staff maintain grooming standard.',3,NULL),
('Sales & Customer',2,'SC2','Staff show good product knowledge.',2,NULL),
('Sales & Customer',3,'SC3','Staff doing suggestive / cross selling.',3,NULL),
('Sales & Customer',4,'SC4','Corporate / school visit / LSM activities tracker updated.',2,NULL),
('Sales & Customer',5,'SC5','Ambient temperature is comfortable for customers.',1,NULL),
('Sales & Customer',6,'SC6','All menu / DNB / marketing collaterals updated and displayed.',1,NULL),
('Product',1,'ST1','Temperature is being tracked.',2,NULL),
('Product',2,'ST2','All equipment gives temperature readings as per SOP.',2,NULL),
('Product',3,'ST3','Receiving process is being followed.',2,NULL),
('Product',4,'ST4','Ordering process for dry, frozen and local purchases is being followed.',2,NULL),
('Product',5,'ST5','Inventory items stored at designated places and arranged FIFO.',2,NULL),
('Product',6,'ST6','Weekly inventory and action-plan process has been followed.',2,NULL),
('Product',7,'ST7','Daily critical inventory process has been followed.',2,NULL),
('Product',8,'ST9','Team is aware of COGS opportunity points from the previous month''s action plan.',2,NULL),
('Product',9,'ST10','Wastages are correctly accounted for in the system.',2,NULL),
('Product',10,'ST11','No expired items lying in store without a "not in use" marking.',2,NULL),
('Product',11,'ST12','Monthly COGS opportunities action plan is displayed in store.',2,NULL),
('Product',12,'ST13','Inter-store transfer process has been followed.',1,NULL),
('People',1,'EM1','Attendance has been correctly and timely updated for all employees.',3,'This would ensure that attendance is correctly recorded.'),
('People',2,'EM2','GAAP has been updated for any employee who has resigned.',2,'This would help ensure the responsibility of the cashier running the till.'),
('People',3,'EM4','Key documents are available in the employee file.',2,'To cross-check whether managers are recording employee overtime properly.'),
('People',4,'EM5','All team members are groomed well as per SOP.',2,NULL),
('Physical Security',1,'PS1','Back entrance / store area is secure; gate pass process is adhered to.',2,NULL),
('Physical Security',2,'PS2','Safe is properly secured and efficiently used.',2,NULL),
('Physical Security',3,'PS3','Safe and safe keys are secured.',1,NULL),
('Physical Security',4,'PS4','CCTV is working properly and covers all POS and the safe.',2,NULL),
('Physical Security',5,'PS5','All required licenses are available.',1,NULL),
('Physical Security',6,'PS6','Store incident management tool is available; emergency response team in place.',1,NULL),
('Physical Security',7,'PS7','All staff in/out movement is tracked by security register.',1,NULL),
('Finance / Cash',1,'CP1','Petty cash expenses and details available with Unit Head.',1,NULL),
('Finance / Cash',2,'CP2','No negative petty cash at restaurant level.',1,NULL),
('Finance / Cash',3,'CP3','All machines and chillers working properly.',1,NULL),
('Finance / Cash',4,'CP4','Unit Head conducts ACE audit every month.',2,NULL),
('Finance / Cash',5,'CP6','Proper procedure followed at time of shift closure.',1,NULL),
('Finance / Cash',6,'CP7','Shift handover process between managers correctly followed.',2,NULL),
('Finance / Cash',7,'CP8','Banking carried out as per defined process.',2,NULL),
('Finance / Cash',8,'CP12','Petty cash policy has been followed.',2,NULL),
('Finance / Cash',9,'CP13','Petty cash vouchers made as per guidelines.',2,NULL)
) AS v(section,item_order,code,text,weight,hint)
WHERE c.section=v.section AND c.item_order=v.item_order;